name: Build for bcgithook

on:
  push:
    paths:
      - .github/workflows/build-bcgithook.yaml
      - bcgithook/**
  pull_request:
    paths:
      - .github/workflows/build-bcgithook.yaml
      - bcgithook/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-quick-examples